### ISSUE TITLE
V5: Oracle Number Field cannot be mapped to Nullable<long> (long?)

### ISSUE THREAD

**Issue by eAndy** [CollaboratingPlatypus/PetaPoco#133]
Column in db is Number Null but want to map it into a Long? but get an exception.

using V5 the Database.TT fails on generation

Error	7	Test 'ManagementService.Tests.ActivityTests.GetAlls' failed: System.InvalidCastException : Invalid cast from 'System.Decimal' to 'System.Nullable`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'.
at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
at System.Decimal.System.IConvertible.ToType(Type type, IFormatProvider provider)
at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
at PetaPoco.Database.PocoData.<>c__DisplayClass3b.<GetConverter>b__37(Object src) in C:\Data Files\Code\Open\Filler\ServiceLayer\Main\UnitTests\ManagementService.Tests\Models\PetaPoco.cs:line 2095
at petapoco_factory_0(IDataReader )
at PetaPoco.Database.<Query>d__7`1.MoveNext() in C:\Data Files\Code\Open\Filler\ServiceLayer\Main\UnitTests\ManagementService.Tests\Models\PetaPoco.cs:line 780
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at ManagementService.Tests.Models.DBManager.GetActivities() in C:\Data Files\Code\Open\Filler\ServiceLayer\Main\UnitTests\ManagementService.Tests\Models\DBManager.cs:line 23
at ManagementService.Tests.ActivityTests.GetAlls() in C:\Data Files\Code\Open\Filler\ServiceLayer\Main\UnitTests\ManagementService.Tests\Activity.UnitTests.cs:line 27	C:\Data Files\Code\Open\Filler\ServiceLayer\Main\UnitTests\ManagementService.Tests\Models\PetaPoco.cs	2095

**Comment by pleb** [comment]
I hope somebody with Oracle can contribute a PR for this :smiley:

**Comment by havotto** [comment]
I don't think this is a bug. [Here](https://docs.oracle.com/cd/B19306_01/olap.102/b14346/dml_datatypes002.htm#CJACDECG) are the Oracle numeric data types, and NUMBER is fractional. That's why the data provider returns Decimal. LONGINTEGER is like long.
Maybe a custom mapper overriding GetFromDbConverter() could help?

**Comment by pleb** [comment]
agree with @havotto (thanks) that this is not a bug. Please see Sqlite integration [SqliteMapper] (https://github.com/CollaboratingPlatypus/PetaPoco/blob/master/PetaPoco.Tests.Integration/Databases/Sqlite/SqliteDBTestProvider.cs) for an example of to implement a custom mapper
