### ISSUE TITLE
Stange issue I cannot resolve where the field and values in the returned DataReader are from the previous query

### ISSUE THREAD

**Issue by phkendall** [CollaboratingPlatypus/PetaPoco#154]
I'm sure if this is the correct place to submit this issue, but here goes anyway.

I have been using PetaPoco in a heavily used ASP.NET production system since October 2012. We run in a .net 2.0 runtime, compiled with the flag PETAPOCO_NO_DYNAMIC. Everything has been working great until about a week ago, when after no changes to the code, we started getting strange exceptions in the PetaPoco code. These exceptions only occur after a number of hours of usage on busy days. Recycling the IIS application pool cures the problem for a few hours (up to 10 or 15), but then if the server remains heavily used the problem will come back. Here is an example exception:

System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.  
 at System.Data.SqlClient.SqlBuffer.get_String()  
 at petapoco_factory_0(IDataReader )  
 at petapoco_multipoco_factory(MultiPocoFactory , IDataReader , Object )  
 at PetaPoco.Database.<Query>d__1a`1.MoveNext()    
 at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)  
 at XXX.XXX.SplitData.Repositories.PostAllocationTaskRepository.Get(String jobPlanId)

To help diagnose the problem I placed some trace output into the PetaPoco.Database.Query<TRet>(Type[] types, object cb, string sql, params object[] args) method like so:

TRet poco;
try
{
  if (!r.Read())
 break;
                                poco = factory(r, cb);
    }
    catch (Exception x)
    {
                                System.Diagnostics.Trace.WriteLine(string.Format("## Query ##"));
                                System.Diagnostics.Trace.Indent();

```
                            System.Diagnostics.Trace.WriteLine(string.Format("SQL: '{0}'", sql));

                            Object[] values = new Object[r.FieldCount];
                            int fieldCount = r.GetValues(values);
     for (int i = 0; i < fieldCount; i++)
     {
                                System.Diagnostics.Trace.WriteLine(string.Format("Reader Value: '{0}', '{1}'", i, values[i]));
    }
                            foreach (var arg in args)
                            {
                                System.Diagnostics.Trace.WriteLine(string.Format("ARGS: '{0}'", arg));
                            }
                            System.Diagnostics.Trace.WriteLine(string.Format("Culture: {0}", Thread.CurrentThread.CurrentCulture.Name));
                            System.Diagnostics.Trace.WriteLine(string.Format("Culture Decimal Separator: {0}", Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator));
                            System.Diagnostics.Trace.WriteLine(string.Format("Culture Positive sign: {0}", Thread.CurrentThread.CurrentCulture.NumberFormat.PositiveSign));
                            System.Diagnostics.Trace.Unindent();

                            OnException(x);
                            throw;
```

}

Below is the trace output from two consecutive queries (the first query caused the exception above):

00832529    12:02:09    [10688] ## Query ##  
00832530    12:02:09    [10688]  
00832531    12:02:09    [10688] SQL: 'SELECT PostAllocationTasks._, PostAllocationTaskStatuses._  
00832532    12:02:09    [10688] FROM dbo.PostAllocationTasks  
00832533    12:02:09    [10688] INNER JOIN dbo.PostAllocationTaskStatuses  
00832534    12:02:09    [10688] ON PostAllocationTasks.StatusId = PostAllocationTaskStatuses.Id 
00832535    12:02:09    [10688] WHERE (JobPlanId = @0)'  
00832536    12:02:09    [10688]  
00832537    12:02:09    [10688] Reader Value: '0', '1'  
00832538    12:02:09    [10688]  
00832539    12:02:09    [10688] ARGS: 'IP1008197'  
00832540    12:02:09    [10688]  
00832541    12:02:09    [10688] Culture: en-GB  
00832542    12:02:09    [10688]  
00832543    12:02:09    [10688] Culture Decimal Separator: .  
00832544    12:02:09    [10688]  
00832545    12:02:09    [10688] Culture Positive sign: +    

00832546    12:02:11    [10688] ## Query ##  
00832547    12:02:11    [10688]  
00832548    12:02:11    [10688] SQL: 'SELECT JobFinancialsView._, RateCodesView._  
00832549    12:02:11    [10688] FROM JobFinancialsView  
00832550    12:02:11    [10688] INNER JOIN RateCodesView  
00832551    12:02:11    [10688] ON JobFinancialsView.RateCode = RateCodesView.Id  
00832552    12:02:11    [10688] WHERE (JobId = @0)  
00832553    12:02:11    [10688] ORDER BY OrderIndex, RateCode'  
00832554    12:02:11    [10688]  
00832555    12:02:11    [10688] Reader Value: '0', 'IP1008197'  
00832556    12:02:11    [10688]  
00832557    12:02:11    [10688] Reader Value: '1', '19/02/2013 11:54:06'  
00832558    12:02:11    [10688]  
00832559    12:02:11    [10688] Reader Value: '2', '19/02/2013 11:54:15'  
00832560    12:02:11    [10688]  
00832561    12:02:11    [10688] Reader Value: '3', '19/02/2013 11:55:46'  
00832562    12:02:11    [10688]  
00832563    12:02:11    [10688] Reader Value: '4', '2'  
00832564    12:02:11    [10688]  
00832565    12:02:11    [10688] Reader Value: '5', '0.60'  
00832566    12:02:11    [10688]  
00832567    12:02:11    [10688] Reader Value: '6', 'A critical error occured. The error has been logged, please contact your system administrator.'  
00832568    12:02:11    [10688]  
00832569    12:02:11    [10688] Reader Value: '7', '2'  
00832570    12:02:11    [10688]  
00832571    12:02:11    [10688] Reader Value: '8', 'Failed'  
00832572    12:02:11    [10688]  
00832573    12:02:11    [10688] ARGS: 'J09734'  
00832574    12:02:11    [10688]  
00832575    12:02:11    [10688] Culture: en-GB  
00832576    12:02:11    [10688]  
00832577    12:02:11    [10688] Culture Decimal Separator: .  
00832578    12:02:11    [10688]  
00832579    12:02:11    [10688] Culture Positive sign: + 

The odd thing I cannot work out is looking at the trace output, the reader values in the second query are the results  from the first query. To me it appears that the previous reader is being used by the query, however I cannot understand how that could possibly happen.

Has anyone else experienced anything like this and can help me shed some light on it?

Thanks in advance

**Comment by BobT2022** [comment]
Bizarrely I'm also getting this issue sporadically and when calling a s/procedure to return a single record to hydrate an ORM domain model type.

I'm using PetaPoco v6.0.524 and Microsoft.Data.SqlClient v5.0.0 via a derived SqlServerDatabaseProvider class that allows me to override the GetFactory() method (and hence to use Microsoft.Data.SqlClient v5.0.0 rather than the standard System.Data.SqlClient v4.0.0 assembly).

I'm using .NET 5 and the following internal diagnostic trace log (of which includes a custom PetaPocoLoggingEventHandlers type to handle PetaPoco events, and a IUnitOfWork type that acts as a transactional wrapper around the PetaPoco Database instance).

This bug is really bizarre in that calling my REST API function in question (which calls the code stack below) works 99.99% of the time, but then presents the following "Unable to cast error" 0.01% of the time (the % representation may be exaggerated but literally seems that infrequent). Each API function call creates a new PetaPoco instance (and thus a new Database instance, and correspondingly a new DB connection), and no DB transaction applies (since I'm reading logical record locking state info. only).

I can't however replicate the issue in code as I can't see what the natural trigger for the exception would be, given that running the SQL in question (a s/proc taking two parameters and returning a single data row [all redacted] works 100% of the time as expected, returning the correct data columns with the correct data types).

```
2022-09-14T11:08:35.6072195+01:00 0HMKM72GH6DQ6:00000002 [ERR] The database operation failed due to an exception running the command [dbo.****
	 -> @0 [String] = "***"
	 -> @1 [String] = "***"] against DB [****]: Unable to cast object of type 'System.DateTime' to type 'System.Int32'. [Thread ID: 14] [Inner Exception: n/a] (2ae7b9a2)
2022-09-14T11:08:35.6076036+01:00 0HMKM72GH6DQ6:00000002 [VRB] Connection Closed for [****]. KeepConnectionAlive: [False] [Thread ID: 14] (f335d909)
2022-09-14T11:08:35.6281479+01:00 0HMKM72GH6DQ6:00000002 [ERR] Unable to cast object of type 'System.DateTime' to type 'System.Int32'.
   at Microsoft.Data.SqlClient.SqlBuffer.get_Int32()
   at petapoco_factory_0(IDataReader )
   at PetaPoco.Database.ExecuteReaderAsync[T](Action`1 processPoco, CancellationToken cancellationToken, CommandType commandType, String sql, Object[] args)
   at ****.PetaPocoLoggingEventHandlers.OnExceptionThrown(Object sender, ExceptionEventArgs e)
   at PetaPoco.Database.OnException(Exception x)
   at PetaPoco.Database.ExecuteReaderAsync[T](Action`1 processPoco, CancellationToken cancellationToken, CommandType commandType, String sql, Object[] args)
   at PetaPoco.Database.FetchProcAsync[T](CancellationToken cancellationToken, String storedProcedureName, Object[] args)
   at ****.GetObjectLockStatus(IUnitOfWork unitOfWork, String sourceRef, String sourceObjectClass, CancellationToken cancellationToken)
   at ****.ObjectLockingController.GetObjectLockStatus(String sourceRef, String sourceObjectClass, CancellationToken cancellationToken)
   at lambda_method653(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) (6dc15af5)
```

**Comment by BobT2022** [comment]
Does look like https://github.com/CollaboratingPlatypus/PetaPoco/pull/129 needs to be done as https://stackoverflow.com/a/19664437/2270895 points out the issue using ReaderWriterLockSlim with async/await (which in my case I am using extensively).

Not quite sure where to go from here as I'd rather not make my large code base work synchronously and whilst a sporadic issue remains nonetheless a significant issue for us.

**Comment by pleb** [comment]
@BobT2022 I'm a little busy that the moment. Any chance you could do the work and submit a PR?

**Comment by asherber** [comment]
I'm not sure whether this will fix the hard-to-reproduce reported issue, but #655 (borrowing from @jpshannon) achieves the goal of replacing the Dictionary/ReaderWriterLockSlim in the Cache class.

**Comment by pleb** [comment]
Released and is a part of the https://www.nuget.org/packages/PetaPoco.Compiled/6.0.530-beta and https://www.nuget.org/packages/PetaPoco.Compiled/6.0.532 packages

**Comment by pleb** [comment]
@BobT2022 let us know how you go with the changes ;)

**Comment by BobT2022** [comment]
@pleb @asherber Very much appreciated, I know you're both extremely busy! I'll let you know :)

**Comment by BobT2022** [comment]
I've good news in that I believe I've found the problem, albeit it's _not_ a PetaPoco issue.

To explain:

After updating my implementation code to use the PetaPoco 6.0.532 package version kindly provided above, I was still observing the issue albeit still sporadically (i.e., < 0.01% of the time in over 50,000 invocations of my library code). As a sanity check I even changed my methods under test to be _synchronous_ to rule out any lingering problems with async/await use; however, the same issue persisted.

So I looked at the data source (a s/proc) which is designed to return information about a business process lock held against a source data record. This s/proc returns null values for certain columns where no business process lock has been acquired (who owns the lock [an integer column] and when was the lock established [a date/time column]).

**_However_** it appears that calling GetSchemaTable on the IDataReader (to determine the data type of the destination property with the innards of the PetaPoco dynamic factory function [DynamicMethod] that converts a IDataReader record into a POCO object) returns an Int data type for any column value that is NULL.

**Comment by BobT2022** [comment]
Hi @asherber, can't use LinqPad but a console app shows effectively the same thing:

![image](https://user-images.githubusercontent.com/89731356/192299251-d2ace4f4-7928-41a9-81a2-ec8119cb7f1e.png)


Interestingly this SO post https://stackoverflow.com/questions/73296995/sqldatareader-getschematable-returns-data-type-int-when-all-values-are-null reports _"...The default data type of NULL returned by SQL Server is int..."_ which is highly suggestive of the underlying issue at the heart of the problem.

In my case the s/proc is returning a row but because there's no values for the locked by / locked at columns, and despite adding an explicit CAST(NULL AS DATETIME) around the Locked At column (to denote no lock exists yet the column value should be handled per its DateTime? property POCO declaration) the issue remains.

I have refactored my code such that the s/proc returns no record at all to denote no lock exists, so having the underlying code handle the creation of the POCO manually (leaving the Locked By and Locked At properties to their default null values).

Thanks.

**Comment by asherber** [comment]
@BobT2022 I guess I'm wondering if you have correctly diagnosed the issue. Your previous comment implied that the problem was Sql Server returning an int type of null. But as my code shows (and your console app confirms), PP has no problems turning that null int into a null DateTime.

Are you able to provide a minimal example in C# that uses PP and demonstrates the problem?

**Comment by BobT2022** [comment]
@asherber It's more than likely I've missed something as other such code where null column values are mapped to nullable POCO properties seem to be Ok. I'll try and create a simple repro as soon as I can. Thanks for your help, much appreciated :)

**Comment by BobT2022** [comment]
@asherber Quick update - can't seem to replicate outside my wider application code, so I'll try and repro this issue as and when I can in the background. Thanks for the effort on the Cache class change though, much appreciated.
