### ISSUE TITLE
Query<dynamic> broken in PetaPoco.Core.Compiled 5.1.280

### ISSUE THREAD

**Issue by asherber** [CollaboratingPlatypus/PetaPoco#430]
The following line of code works in NuGet version 5.1.259 but throws an exception in 5.1.280:
```csharp
var records = db.Query<dynamic>("SELECT * FROM MyTable");
```
Stack trace is:
```
System.NullReferenceException
Object reference not set to an instance of an object.
   at PetaPoco.ConventionMapper.<>c.<.ctor>b__36_8(PropertyInfo pi, Type t) in C:\projects\petapoco\PetaPoco\Core\ConventionMapper.cs:line 160
   at PetaPoco.ConventionMapper.GetFromDbConverter(PropertyInfo targetProperty, Type sourceType) in C:\projects\petapoco\PetaPoco\Core\ConventionMapper.cs:line 211
   at PetaPoco.Core.PocoData.<>c__DisplayClass29_0.<GetFactory>b__0() in C:\projects\petapoco\PetaPoco\Core\PocoData.cs:line 143
   at PetaPoco.Internal.Cache`2.Get(TKey key, Func`1 factory) in C:\projects\petapoco\PetaPoco\Utilities\Cache.cs:line 47
   at PetaPoco.Core.PocoData.GetFactory(String sql, String connectionString, Int32 firstColumn, Int32 countColumns, IDataReader reader, IMapper defaultMapper) in C:\projects\petapoco\PetaPoco\Core\PocoData.cs:line 120
   at PetaPoco.Database.<Query>d__49`1.MoveNext() in C:\projects\petapoco\PetaPoco\Database.cs:line 975
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PetaPoco.Database.Fetch[T](String sql, Object[] args) in C:\projects\petapoco\PetaPoco\Database.cs:line 712
   at AdvantageDatabaseProvider.Tests.Tests.Can_Query() in P:\CSharpApps\Nuget\PetaPoco.AdvantageDatabaseProvider\AdvantageDatabaseProvider.Tests\Tests.cs:line 38
```

**Comment by asherber** [comment]
The stack trace I posted happens to use `Fetch()` with a `DatabaseProvider` that I'm writing, but the same issue exists with `Query()` and the SQLite provider.

**Comment by asherber** [comment]
Possibly related to #415

**Comment by pleb** [comment]
Released to master today
