### ISSUE TITLE
Postgres Support Broken: Npgsql 3.x removed support for writing a parameter with an IEnumerable value, use .ToList()/.ToArray() instead

### ISSUE THREAD

**Issue by groogiam** [CollaboratingPlatypus/PetaPoco#611]
It appears PetaPoco support for npgsql 3 is broken. Attempts to perform any parameterized database operations result in

Npgsql 3.x removed support for writing a parameter with an IEnumerable value, use .ToList()/.ToArray() instead
   at Npgsql.TypeMapping.ConnectorTypeMapper.GetByClrType(Type type)
   at Npgsql.NpgsqlParameter.ResolveHandler(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.ValidateParameters(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken)
   at PetaPoco.Database.<>c__DisplayClass347_0.<<ExecuteScalarHelperAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at PetaPoco.Database.CommandHelper(CancellationToken cancellationToken, DbCommand cmd, Func`3 cmdFunc)
   at PetaPoco.Providers.PostgreSQLDatabaseProvider.ExecuteInsertAsync(CancellationToken cancellationToken, Database db, IDbCommand cmd, String primaryKeyName)
   at PetaPoco.Database.ExecuteInsertAsync(CancellationToken cancellationToken, String tableName, String primaryKeyName, Boolean autoIncrement, Object poco)

**Comment by groogiam** [comment]
Nevermind, this was user error. A hashset property was added to the poco without being ignored.

**Comment by blorange2** [comment]
I've ran into a similar issue but am not to knowledgeable in regards to C#, was it an easy fix?

**Comment by blorange2** [comment]
@groogiam hey again, I don't suppose you know why this actually fixes the issue? I basically got handed a project recently with this issue and it arises when PetaPoko tries to perform an update on a model's attributes.

I come from a Java/ PHP background so am still getting a feel for everything.

**Comment by asherber** [comment]
I think it's two things. It looks like @groogiam was passing a POCO to `ExecuteInsertAsync()`. This basically uses the property names on the POCO to locate columns in the table and then populates the columns with the values of the properties. In general, you want to use properties that have value-type values, since SQL databases don't know how to store complex objects like lists. Adding the `[Ignore]` attribute tells PetaPoco not to use that property and its value in constructing the SQL insert statement.

The error message was a little bit of a red herring. There are times when you can pass in a list as a SQL parameter, usually when calling a stored proc or function, but Postgres 3.0 they only allows you to use `IList`, `IList<T>`, or array. `HashSet<T>` is none of those things.

So the error was thrown because he passed in an enumerable as a parameter that wasn't a list or array, but then he realized that he didn't mean to include that property in the insert at all.

**Comment by blorange2** [comment]
Thanks both for the answers, I will check over what I can see to see if I'm passing anything that should be a list. 

In my particular scenario I can see it's calling an Update function with 3 parameters, the third being a POCO that is a model.

I can also see that is you follow the PetaPoko methods down they eventually iterate through the columns.

I'm thinking maybe one of my model's properties is being converted but I'll just need to check.

I'm assuming it'd be incorrect to bluntly change everything to a List?

I'll have another look given what you've both said.

**Comment by asherber** [comment]
I can't answer that without knowing more about your code and your table. My first instinct is to say that if you're calling an update, the properties on your poco should probably all be value types, or you should use the `Ignore` attribute on reference types. All of the properties on your poco get converted to SQL parameters and passed in with an `UPDATE` query, unless they've got `Ignore`.
